### ISSUE TITLE
Use-case review

### ISSUE THREAD

**Issue by hans-lizihan** [comp4007-group6/atm-ss#1]
![usecase](https://cloud.githubusercontent.com/assets/7879022/10635366/cead8164-782a-11e5-8587-37d56f2962b7.png)

Please **comment** below to approve this use case diagram.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by hans-lizihan** [comment]
@WinonaLyw @marianachow2004 @ljs3roy 先看一眼 usecase 这个很快 打钩之后可以 close 了

**Comment by marianachow2004** [comment]
1. Operator's one should be maintenance?? 
2. There is no different between transfer cheque or cash in our case, so we should combine it?
3. Change Setting or Get Envelope could also print advise?? (I know you mention in F08#01, but just want to confirm) Thanks!!!!!!!

**Comment by hans-lizihan** [comment]
@marianachow2004 
1. updated
2. for readability, I think it is okay
3. because <<extend>> is optional, so print advice is okay
