### ISSUE TITLE
State Master UML review

### ISSUE THREAD

**Issue by xiaoyufan** [comp4007-group6/atm-ss#10]
![state - master](https://cloud.githubusercontent.com/assets/15053186/10662813/86c64984-78e9-11e5-96b7-68bce06e6b8d.png)

:bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: 

Please **comment** below to approve this diagram.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by WinonaLyw** [comment]
idle ---> maintenance : wrong triggers on the arrows!!!

**Comment by xiaoyufan** [comment]
@WinonaLyw oh oh wrong direction! Thanks~
