### ISSUE TITLE
State advicePrinter UML Diagram

### ISSUE THREAD

**Issue by ljs3roy** [comp4007-group6/atm-ss#11]
![adviceprinter - uml state diagram](https://cloud.githubusercontent.com/assets/15083313/10691774/6a181de6-79be-11e5-8a5e-846129843d39.png)

**Description:**
The advice printer will remain idle until system wants it to print advice on user's demand or print slip when user want to make deposit. During this process, if the advice printer find itself out of paper or being jammed, it will send "out of paper" or "printer jammed" message to the system and the system will set it to offline state. Otherwise, after the printer finish the work, it will return to idle until next instruction.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by xiaoyufan** [comment]
typo in the state "Priting" (should be "Printing")

**Comment by ljs3roy** [comment]
@xiaoyufan Roger that

**Comment by WinonaLyw** [comment]
@xiaoyufan actually what is the difference of "out of service" and "offline", I forgot ....some diagrams have "out of service" state

**Comment by xiaoyufan** [comment]
@WinonaLyw "offline" is "off" that is triggered by "shutdown" command
