### ISSUE TITLE
State cardReader UML Diagram

### ISSUE THREAD

**Issue by ljs3roy** [comp4007-group6/atm-ss#12]
![cardreader - uml state diagram](https://cloud.githubusercontent.com/assets/15083313/10692432/17eb779c-79c4-11e5-9e3b-b85a8b8e0f9c.png)

**Description:**
The  card reader will remain idle until a card is inserted leading the card reader to reading the card. During this process, if the card reader find itself been jammed or has hardware failure for reading, it will send  "jammed"/"hardware failure" message to the system and the system will send among to set it to offline state. Otherwise, if the card is indicated invalid by the system and the card reader will be instructed to ejecting card until the card is taken by the user then it will back to idle state, the same state flow for transaction finished successfully and user wants to eject the card. Or if the system instructs it to retain the card, it will do it and back to idle state. 

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by xiaoyufan** [comment]
@WinonaLyw @ljs3roy how about change "ATM-SS signal" to "eject card" or simply "eject"?
