### ISSUE TITLE
State depositCollector UML Diagram

### ISSUE THREAD

**Issue by ljs3roy** [comp4007-group6/atm-ss#13]
![depositcollector - uml state diagram](https://cloud.githubusercontent.com/assets/15083313/10692135/d122c7f4-79c1-11e5-9ab9-27c9196873d4.png)

**Description:**
The deposit collector stays in "Closed" state until the ATM sends "open" command to it and it will enter "Opened" state. In "Opened" state, it will prompt the customer to press continue key or cancel the deposit transaction if no envelop is inserted in 30 seconds. If the transaction is canceled or the insertion has been completed, the collector will return to "Closed" state. In the "Opened" state, it will enter "Offline" state with reporting error message to the ATM if critical hardware failures occur. 

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by hans-lizihan** [comment]
1. opened --> opened 这个关系是不是不太对 
2. opened --> closed 是不是应该是 close

@WinonaLyw
