### ISSUE TITLE
State cashDispenser UML Diagram

### ISSUE THREAD

**Issue by ljs3roy** [comp4007-group6/atm-ss#14]
![cashdispenser - uml state diagram](https://cloud.githubusercontent.com/assets/15083313/10692192/600ccbc2-79c2-11e5-9e25-ed14f0f894e6.png)

**Description:**
The cash dispenser will remain idle until system wants it to dispense money notes for user withdrawal. Before this process, if the cash dispenser will check the notes inventory, and send the amount of the denominations to the system, if the notes are not enough for user requirement. it will be set back to idle until next instruction. But if all notes are run out, the system will set it to offline. Like other hardwares, if it find itself  has hardware failure during the service, it will send signal to system and system will set it to offline. Otherwise, if everything is right, it will ejecting exact amount of money until the money is taken by the user,and then back to idle until next instruction.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by WinonaLyw** [comment]
out of inventory will not go to offline ? since no envelop will lead to offline...

**Comment by hans-lizihan** [comment]
@WinonaLyw
