### ISSUE TITLE
State keyPad UML Diagram

### ISSUE THREAD

**Issue by ljs3roy** [comp4007-group6/atm-ss#16]
![keypad - uml state diagram](https://cloud.githubusercontent.com/assets/15083313/10692329/66e52006-79c3-11e5-9ace-d8b5ced2de33.png)

**Description:**
The KeyPad emitter will stay idle, until the system send signal to it to record user's input.Then, it will be reading keys. After user completes typing, it will be set back to idle. During the process, if the keypad emitter find itself having hardware failure, it will send "hardware failure" signal to the system and it will then be set offline by the system.

Please **comment** below to approve this diagram.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [X] Roy
- [X] Hans

**Comment by xiaoyufan** [comment]
@ljs3roy @WinonaLyw change "keypad damaged" to "[has hardware failure]"? (hardware failure involves other types of problems in addition to keypad damaged)

**Comment by ljs3roy** [comment]
@xiaoyufan It is ok.

**Comment by ljs3roy** [comment]
@xiaoyufan Do all changes after discussion tomorrow.

**Comment by xiaoyufan** [comment]
@ljs3roy delete "out of service"
