### ISSUE TITLE
Bug of CANCEL BUTTON

### ISSUE THREAD

**Issue by ljs3roy** [comp4007-group6/atm-ss#20]
Process: ReadCard -> InputPassword -> Set Keypad Status "OFF" -> The screen should display "Machine Out of Service" and Retain Card -> However, press CANCEL button -> Screen display "get your card back" -> Press "Send to ATMSS" button on CardReader -> one new card could be read.

**Comment by hans-lizihan** [comment]
Banned sending message to ATM when keypad is off
