### ISSUE TITLE
Testing - Cash note don't update in card inserting view

### ISSUE THREAD

**Issue by marianachow2004** [comp4007-group6/atm-ss#25]
Test Path:
1. select withdrawal service
2. select account 03
3. input amount $1000
4. back to menu and print advice
5. select withdrawal service
6. select account 02
7. input amount $400
8. back to menu and print advice
9. select withdrawal service
10. select account 01
11. input amount $100
12. eject card

OR

1. check out of cash note "100", "500", "100"
2. select withdrawal service
3. select account 01
4. input amount $1500
5. eject card

** the system know the cash note is not enough, but only don't update the screen

**Comment by hans-lizihan** [comment]
fixed
