### ISSUE TITLE
Activity login UML review

### ISSUE THREAD

**Issue by hans-lizihan** [comp4007-group6/atm-ss#3]
![login](https://cloud.githubusercontent.com/assets/7879022/10689288/74d5b5e8-79ac-11e5-9f01-b4e7c0da7396.png)

Please **comment** below to approve this diagram.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by WinonaLyw** [comment]
perform transaction can be system show main menu screen

**Comment by marianachow2004** [comment]
为什么Eject Card 跟Read card number 和Check connection是同步进行???
