### ISSUE TITLE
Activity Withdraw UML review

### ISSUE THREAD

**Issue by xiaoyufan** [comp4007-group6/atm-ss#4]
![activity - withdraw](https://cloud.githubusercontent.com/assets/15053186/10693630/0c63039c-79cc-11e5-89d4-67dfe8271228.png)

Please **comment** below to approve this diagram.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by WinonaLyw** [comment]
the option to view balance?

**Comment by xiaoyufan** [comment]
@WinonaLyw I changed the last activity to "show success view" in all activity diagrams. Is it ok?

**Comment by WinonaLyw** [comment]
@xiaoyufan but no enough balance also ends in this activity....?

**Comment by WinonaLyw** [comment]
@xiaoyufan @hans-lizihan successful view is before or after print advice? this one differs from transfer diagram....

**Comment by hans-lizihan** [comment]
@WinonaLyw we have diff opinions on this see #7 

And I think the activity should stop whenever it reaches :show success view; because #2 has shown this logic

**Comment by marianachow2004** [comment]
Withdrawal success 也不用print advise 嗎？？

**Comment by xiaoyufan** [comment]
@marianachow2004 现在是将print 包含在show success view里了，这样可以少画几步，看起来清楚些

**Comment by marianachow2004** [comment]
好的，明白了，謝謝！！

**Comment by xiaoyufan** [comment]
@marianachow2004 
:smile: :smile:
