### ISSUE TITLE
Activity Transfer UML review

### ISSUE THREAD

**Issue by xiaoyufan** [comp4007-group6/atm-ss#5]
![activity - transfer](https://cloud.githubusercontent.com/assets/15053186/10693518/4815e6da-79cb-11e5-9223-38951a664225.png)

Please **comment** below to approve this use case diagram.

- [x] Xiao yu A
- [ ] Xiao yu B
- [ ] Mariana
- [ ] Roy
- [ ] Hans

**Comment by WinonaLyw** [comment]
typo on the "transferee" in the last activity in bank lane.

**Comment by hans-lizihan** [comment]
@xiaoyufan 我把最后的 ending 都改成了 show operation success view --> flow final

**Comment by xiaoyufan** [comment]
@WinonaLyw oh oh wrong direction! Thanks~

**Comment by xiaoyufan** [comment]
@WinonaLyw changed

**Comment by hans-lizihan** [comment]
@xiaoyufan 你最后那个 condition 画多了吧 
还有既然是直接进了 show success view 那最后的fork 和判断 print advice 就都可以省了 #2

**Comment by xiaoyufan** [comment]
@hans-lizihan how about this?

**Comment by hans-lizihan** [comment]
@xiaoyufan success view --> stop. Delegate condition to :Show success view;

**Comment by xiaoyufan** [comment]
@hans-lizihan if exceptions such as "balance not enough" occur, still need to print advice without showing success view

**Comment by hans-lizihan** [comment]
@xiaoyufan  see #7

**Comment by xiaoyufan** [comment]
@hans-lizihan i don't agree. we'd better discuss this tmr
