### ISSUE TITLE
Activity Deposit UML review

### ISSUE THREAD

**Issue by hans-lizihan** [comp4007-group6/atm-ss#7]
![deposit](https://cloud.githubusercontent.com/assets/7879022/10692612/53e254c2-79c5-11e5-9b35-74f7cabee12a.png)

Please **comment** below to approve this diagram.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by WinonaLyw** [comment]
main flow is ok

**Comment by hans-lizihan** [comment]
@WinonaLyw on transaction succeed now shows the operation success view. see #2

**Comment by marianachow2004** [comment]
wait for 10 seconds 后可以多加一个condition类似是received response, yes 就close slot?? 现在有点感觉像是一定会display timeout message的样子?

**Comment by hans-lizihan** [comment]
@marianachow2004  wait for就是一定会 display timeout. 因为我们已经wait 了 10s

**Comment by marianachow2004** [comment]
@hans-lizihan okay got it!
