### ISSUE TITLE
Use-case description review

### ISSUE THREAD

**Issue by hans-lizihan** [comp4007-group6/atm-ss#8]
[Usecase description.docx](https://github.com/comp4007-group6/atm-ss/files/17693/Usecase.description.docx)

Please **comment** below to approve

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by hans-lizihan** [comment]
1. Maintenance mode should be F10
see https://github.com/comp4007-group6/atm-ss/blob/master/docs/SRS.md#f10

2. As we discussed on 2015-10-19,  我们应该回到 operation success view 让 user choose next step

**Comment by hans-lizihan** [comment]
1. Transaction: Transaction complete --> Prompt success view for the user to choose to 
    1. Print advice and back to main menu
    2. Print advice and eject
    3. Eject
    4. Back to main menu.
2. Transfer: reference to #5 for the steps
    1. failed condition += "The transferor's balance is not enough" 
    2. In *Alternative flows and exception* section, change **use** to **user**
    3. ATM **DO NOT NEED** to check balance at step 3/4, only check balance whenever necessary
3. Deposit: reference to #7 for the steps
    1. the user should be prompt for **Get an envelop** first then select an account
    2. ATM **DO NOT NEED** to check balance at step 3/4, only check balance whenever necessary
4. Withdrawal: reference to #4 
    1. ATM should check weather it has enough inventory then ask BAMS for updating balance

**Comment by marianachow2004** [comment]
i updated the doc in google drive
