### ISSUE TITLE
Activity Change Setting UML review

### ISSUE THREAD

**Issue by hans-lizihan** [comp4007-group6/atm-ss#9]
![changepassword](https://cloud.githubusercontent.com/assets/7879022/10689341/134f1bce-79ad-11e5-81d3-cffd038e1c32.png)

Please **comment** below to approve this use case diagram.

- [x] Xiao yu A
- [x] Xiao yu B
- [x] Mariana
- [x] Roy
- [x] Hans

**Comment by WinonaLyw** [comment]
need to compare the two newly input PIN, update only when they are the same.

**Comment by hans-lizihan** [comment]
@WinonaLyw  updated

**Comment by xiaoyufan** [comment]
If the two inputs don't match, how about prompting for another try instead of ejecting card?

**Comment by hans-lizihan** [comment]
We **ALWAYS** eject the card whenever user does sth wrong @xiaoyufan

**Comment by xiaoyufan** [comment]
@hans-lizihan then we are too harsh

**Comment by xiaoyufan** [comment]
@hans-lizihan i think this one could be an exception

**Comment by marianachow2004** [comment]
"Change success" could be deleted and point to "Display operation success view" directly??
